# Copyright Greg Haskins All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
FROM _NS_/fabric-buildenv:_TAG_

# fabric configuration locations
ENV FABRIC_CFG_PATH /etc/hyperledger/fabric

# create needed directories
RUN mkdir -p \
  $FABRIC_CFG_PATH \
  /var/hyperledger/production
RUN  sed -i 's/http:\/\/cn\./http:\/\//g' /etc/apt/sources.list \
    && apt-get clean \
    && apt-get update --fix-missing \
    && apt-get install -y libgmp-dev build-essential flex bison \
    && wget -O pbc.tar.gz "https://crypto.stanford.edu/pbc/files/pbc-0.5.14.tar.gz" \
    && mkdir -p /usr/src/pbc \
    && tar -xzf pbc.tar.gz -C /usr/src/pbc --strip-components=1 \
    && cd /usr/src/pbc \
    && chmod +x ./configure \
    && ./configure \
    && make \
    && make install \
    && ldconfig
# fabric configuration files
ADD payload/sampleconfig.tar.bz2 $FABRIC_CFG_PATH

# fabric binaries
COPY payload/orderer /usr/local/bin
COPY payload/peer /usr/local/bin

# softhsm2
COPY payload/install-softhsm2.sh /tmp
RUN bash /tmp/install-softhsm2.sh && rm -f install-softhsm2.sh

# typically, this is mapped to a developer's dev environment
WORKDIR /opt/gopath/src/github.com/hyperledger/fabric
