# Copyright Greg Haskins All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
FROM _BASE_NS_/fabric-baseimage:_BASE_TAG_ as builder
WORKDIR /opt/gopath
RUN mkdir src && mkdir pkg && mkdir bin
ADD . src/github.com/hyperledger/fabric
WORKDIR /opt/gopath/src/github.com/hyperledger/fabric
ENV EXECUTABLES go git curl
RUN sed -i 's/http:\/\/cn\./http:\/\//g' /etc/apt/sources.list \
&& apt-get clean \
&& apt-get update --fix-missing \
&& apt-get install -y libgmp-dev build-essential flex bison \
&& wget -O pbc.tar.gz "https://crypto.stanford.edu/pbc/files/pbc-0.5.14.tar.gz" \
&& mkdir -p /usr/src/pbc \
&& tar -xzf pbc.tar.gz -C /usr/src/pbc --strip-components=1 \
&& cd /usr/src/pbc \
&& chmod +x ./configure \
&& ./configure \
&& make \
&& make install \
&& ldconfig
RUN make configtxgen configtxlator cryptogen peer discover idemixgen

FROM _BASE_NS_/fabric-baseimage:_BASE_TAG_
ENV FABRIC_CFG_PATH /etc/hyperledger/fabric
RUN apt-get update && apt-get install -y jq
VOLUME /etc/hyperledger/fabric
COPY --from=builder /opt/gopath/src/github.com/hyperledger/fabric/.build/bin /usr/local/bin
COPY --from=builder /opt/gopath/src/github.com/hyperledger/fabric/sampleconfig $FABRIC_CFG_PATH
